[2023-01-21T20:37:08.922+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: crypto_coins_etl.calculate_average_price manual__2023-01-21T20:37:00.757190+00:00 [queued]>
[2023-01-21T20:37:08.934+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: crypto_coins_etl.calculate_average_price manual__2023-01-21T20:37:00.757190+00:00 [queued]>
[2023-01-21T20:37:08.935+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T20:37:08.936+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-21T20:37:08.937+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T20:37:08.950+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): calculate_average_price> on 2023-01-21 20:37:00.757190+00:00
[2023-01-21T20:37:08.956+0000] {standard_task_runner.py:55} INFO - Started process 2454 to run task
[2023-01-21T20:37:08.960+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'crypto_coins_etl', 'calculate_average_price', 'manual__2023-01-21T20:37:00.757190+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/crypto_coins_etl.py', '--cfg-path', '/tmp/tmpsutqixl3']
[2023-01-21T20:37:08.964+0000] {standard_task_runner.py:83} INFO - Job 165: Subtask calculate_average_price
[2023-01-21T20:37:09.040+0000] {task_command.py:388} INFO - Running <TaskInstance: crypto_coins_etl.calculate_average_price manual__2023-01-21T20:37:00.757190+00:00 [running]> on host 6256f74551c5
[2023-01-21T20:37:09.109+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=crypto_coins_etl
AIRFLOW_CTX_TASK_ID=calculate_average_price
AIRFLOW_CTX_EXECUTION_DATE=2023-01-21T20:37:00.757190+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-21T20:37:00.757190+00:00
[2023-01-21T20:37:09.123+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/transformers/crypto/crypto_transformer.py", line 66, in cal_avg_price
    must_buy_coins = [x for x in cls._get_avg_price(coins)]
  File "/opt/airflow/plugins/transformers/crypto/crypto_transformer.py", line 40, in _get_avg_price
    coin_id = coin_obj['id']
TypeError: list indices must be integers or slices, not str
[2023-01-21T20:37:09.134+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=crypto_coins_etl, task_id=calculate_average_price, execution_date=20230121T203700, start_date=20230121T203708, end_date=20230121T203709
[2023-01-21T20:37:09.146+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 165 for task calculate_average_price (list indices must be integers or slices, not str; 2454)
[2023-01-21T20:37:09.173+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-21T20:37:09.192+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
