[2023-01-21T20:51:42.932+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: crypto_coins_etl.cal_avg_price_using_coin_history manual__2023-01-21T20:51:35.688584+00:00 [queued]>
[2023-01-21T20:51:42.943+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: crypto_coins_etl.cal_avg_price_using_coin_history manual__2023-01-21T20:51:35.688584+00:00 [queued]>
[2023-01-21T20:51:42.944+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T20:51:42.945+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-21T20:51:42.946+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T20:51:42.959+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): cal_avg_price_using_coin_history> on 2023-01-21 20:51:35.688584+00:00
[2023-01-21T20:51:42.965+0000] {standard_task_runner.py:55} INFO - Started process 3443 to run task
[2023-01-21T20:51:42.970+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'crypto_coins_etl', 'cal_avg_price_using_coin_history', 'manual__2023-01-21T20:51:35.688584+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/crypto_coins_etl.py', '--cfg-path', '/tmp/tmpd3fwmu4s']
[2023-01-21T20:51:42.973+0000] {standard_task_runner.py:83} INFO - Job 190: Subtask cal_avg_price_using_coin_history
[2023-01-21T20:51:43.048+0000] {task_command.py:388} INFO - Running <TaskInstance: crypto_coins_etl.cal_avg_price_using_coin_history manual__2023-01-21T20:51:35.688584+00:00 [running]> on host 6256f74551c5
[2023-01-21T20:51:43.117+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=crypto_coins_etl
AIRFLOW_CTX_TASK_ID=cal_avg_price_using_coin_history
AIRFLOW_CTX_EXECUTION_DATE=2023-01-21T20:51:35.688584+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-21T20:51:35.688584+00:00
[2023-01-21T20:51:43.131+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/transformers/crypto/crypto_transformer.py", line 67, in cal_avg_price
    for item in must_buy_coins:
TypeError: _get_avg_price() takes 2 positional arguments but 27 were given
[2023-01-21T20:51:43.141+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=crypto_coins_etl, task_id=cal_avg_price_using_coin_history, execution_date=20230121T205135, start_date=20230121T205142, end_date=20230121T205143
[2023-01-21T20:51:43.153+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 190 for task cal_avg_price_using_coin_history (_get_avg_price() takes 2 positional arguments but 27 were given; 3443)
[2023-01-21T20:51:43.183+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-21T20:51:43.202+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
